In [46]:
import pandas as pd
df=pd.read_csv("C:/Users/snega/Downloads/customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [48]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [49]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [50]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))

In [51]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [52]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'review_rating'],
      dtype='object')

In [53]:
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [54]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [55]:
# new column of age group
labels=["young adult","adult","middle-aged","senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)

In [56]:
df["frequency_of_purchases"].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [57]:
# new column for purchase_frequency_days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90}
df["purchase_frequency_days"]= df["frequency_of_purchases"].map(frequency_mapping)

In [58]:
# to check 2 columns are equal
df[["discount_applied","promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [59]:
(df["discount_applied"]==df["promo_code_used"]).all()  #both has same values in all row

True

In [60]:
df=df.drop("promo_code_used",axis=1)

In [61]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [33]:
!pip install pymysql ipython-sql sqlalchemy cryptography
!pip install --upgrade ipython-sql prettytable

Requirement already satisfied: pymysql in c:\users\snega\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: ipython-sql in c:\users\snega\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in c:\users\snega\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: cryptography in c:\users\snega\anaconda3\lib\site-packages (42.0.5)
Requirement already satisfied: prettytable in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (8.25.0)
Requirement already satisfied: sqlparse in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\snega\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\snega\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\snega\anaconda3\lib\site-packages (from cryptography) (1.16.0)
Requirement already satisfied: pycparser in c:\users\snega\anaconda3\lib\site-packages (from cffi>=1.12->cryptography) (2.21)
Requirement already satisfied: decorator in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\snega\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\snega\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Requirement already satisfied: ipython-sql in c:\users\snega\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\snega\anaconda3\lib\site-packages (3.17.0)
Requirement already satisfied: ipython in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (8.25.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (2.0.30)
Requirement already satisfied: sqlparse in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\snega\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\snega\anaconda3\lib\site-packages (from prettytable) (0.2.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\snega\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\snega\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\snega\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\snega\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\snega\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [37]:
%reload_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%sql mysql+pymysql://root:snega123@localhost:3306/

In [39]:
%%sql
use practice;

 * mysql+pymysql://root:***@localhost:3306/
0 rows affected.

[]

In [66]:
%%sql
show tables;

 * mysql+pymysql://root:***@localhost:3306/
8 rows affected.

[('customer_shopping_behavior_cleaned',),
 ('departments',),
 ('emp1',),
 ('employee',),
 ('employee_bonus',),
 ('employees',),
 ('test_emp',),
 ('test_practice',)]

In [45]:
import pymysql
import pandas as pd

# Use context manager to auto-close connection
with pymysql.connect(
    host='localhost',
    user='root',
    password='snega123',   # put your password
    database='practice'
) as connection:
    query = "select * from employee"
    df = pd.read_sql(query, connection)

print(df.head())

   id   name  managerId  salary
0   1  Alice        NaN   90000
1   2    Bob        1.0   60000
2   3  Carol        1.0   65000
3   4  David        2.0   50000
4   5    Eve        2.0   52000

C:\Users\snega\AppData\Local\Temp\ipykernel_16960\196463844.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

In [62]:
df.to_csv("customer_shopping_behavior_cleaned", index=False)

print("CSV file exported successfully!")

CSV file exported successfully!

In [63]:
import os
print(os.getcwd())

C:\Users\snega

In [64]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:snega123@localhost:3306/practice"
)

In [65]:
df.to_sql(
    name="customer_shopping_behavior_cleaned",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data successfully stored in MySQL!")

Data successfully stored in MySQL!